version: 2.1

orbs:
  docker: circleci/docker@2.2.0
resource_class: medium

jobs:
  project-setup:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout

workflows:
  build-and-push:
    jobs:
      - project-setup
      - docker/publish:
          context:
            - docker
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          extra_build_args: --build-arg ARCH=amd64
          image: $DOCKER_USERNAME/wiserheatingapi
          tag: circleci
      - docker/publish:
          context:
            - docker
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USERNAME
          extra_build_args: --build-arg ARCH=arm64
          image: $DOCKER_USERNAME/wiserheatingapi
          tag: circleci
