version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  project-setup:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout

workflows:
  build-and-push:
    jobs:
      - project-setup
      - docker/publish:
          image: cimeson/wiserheatingapi
          use-docker-credentials-store: true
