version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  build-and-push:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - setup_remote_docker
      - checkout
      - run:
          command: docker buildx create --name multiarch --use
          name: Setup multiarch buildx
      - run:
          command: docker buildx build --push --platform linux/arm64,linux/amd64 -t $CIRCLE_USERNAME/wiserheatingapi:circleci .
          name: Build and push multiarch Docker image

workflows:
  build-and-push:
    jobs:
      - build-and-push
