version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: wiserheatingapi
      - docker/push:
          image: cimeson/wiserheatingapi 

workflows:
  example-workflow:
    jobs:
      - checkout
      - build-docker
