version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build-docker:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker
      - checkout
      - docker/build:
          image: cimeson/wiserheatingapi
      - docker/push:
          image: cimeson/wiserheatingapi 

workflows:
  build-and-push:
    jobs:
      - build-docker
